### PR TITLE
Copy-edit and expand on the initial setup steps in keeper-setup.md

### PR DESCRIPTION
**Pull request by ttmc**
- Finished copy-editing all the grammar and spelling.
- For people who want to run a user/non-authority node, point to Barge.
- Added a subsection listing Additional Support Resources.
- Added a subsection about Types of Keeper Nodes.
- Linked to some best-practices about securing CentOS & Ubuntu.
- Moved all the stuff about ports into a new unordered list.
- Outlined what to do if you don't want to serve websocket requests.

In the configuration file (`config.toml`), I only made one small (but significant) change: I changed the list of APIs served via Websocket from `"all"` to `"pubsub"`. We need to be careful about exposing all the APIs over Websocket, because it's just as powerful a transport as the HTTP one on port 8545.

### CODE REVIEW

**Comment by ttmc** [comment]
I guess the lines in the `[rpc]` section of `config.toml`:

```text
interface = "all"
hosts = ["all"]
```

should be changed to only allow connections via localhost. I will look into how to do that.

**Comment by ttmc** [comment]
The more I think about it, the less I like the idea of an authority node publicly exposing websocket connections, even if they are only serving the pubsub API. If there are enough subscriptions (and the default max is 100), that might create significant load on the authority node. Maybe it would be best to leave the job of serving websocket connections to user/non-authority nodes.

**Comment by jcortejoso** [comment]
Really the interfaces where the parity client is listening does not care at all (in this case), because they refer to interfaces of the docker container that is running parity. To control the interfaces where the ports are exposed have to be done in the systemd unit. For example to expose only locally the port 30303 the user should use: `-p 127.0.0.1:30303:30303/tcp\`.

**Comment by ttmc** [comment]
Ah yes Docker... I guess if Parity Ethereum tries to talk to "localhost" inside the container, then that probably won't work, so I should change the RPC `interface = "local"` back to `interface = "all"` (inside the container) and then map 8545 inside the container to 127.0.0.1:8545 on the container's host.

**Comment by ttmc** [comment]
Yesterday evening, [the following message was written by joshua-mir on the parity-poa Gitter support channel](https://gitter.im/paritytech/parity-poa?at=5cdc35935a887e1cd9f1de86):

`Yes... use min_gas_price, usd_per_tx doesn't mean anything on PoA networks...`

and someone else posted an example with:

`min_gas_price = 0 #min gas price in WEI per GAS unit (0 Ether)`

so I will do a commit to change that (along with some explanation).

**Review by aaitor — APPROVED** [review]

**Pull request merged**
